### PR TITLE
Feature/4 improve auth library

### PR DESCRIPTION
**Pull request by cmcWebCode40**
- [x] Added Design for checkbox
- [x] Added Persistence login feature using local storage
- [x] Installed new dependency(store) for storing data in the local storage

#4

### CODE REVIEW

**Comment by nick-verida** [comment]
This doesn't quite work. If you login without the box checked and then reload the page, the UI for the markdown editor displays (although you don't get your data). 

Steps:

1. Login (without pressing 'remember me' box)
2. Reload page using browser reload
3. UI shows (should show login page instead)

**Review by nick-verida — CHANGES_REQUESTED** [review]
See comment

**Comment by cmcWebCode40** [comment]
> 2\. Reload page using browser reload



> This doesn't quite work. If you login without the box checked and then reload the page, the UI for the markdown editor displays (although you don't get your data).
> 
> Steps:
> 
> 1. Login (without pressing 'remember me' box)
> 2. Reload page using browser reload
> 3. UI shows (should show login page instead)

This PR is linked to this issue from the markdown [issue #18](https://github.com/verida/markdown-notes-demo/issues/18) which I'm currently working on, I will notify you when I open a new PR,  I only worked on the checkbox and the function that saves the user data in the local storage for this PR

**Review by nick-verida — APPROVED** [review]
I understand the bug I found was in the Markdown editor, not here now. 

This looks good

**Pull request merged**
