### PR TITLE
Feature/5 redesign auth modal UI #5

### PR DESCRIPTION
**Pull request by cmcWebCode40**
- [x]  Redesigned the QR modal User Interface a demo image is attached below

verida_modal_preview

### CODE REVIEW

**Comment by tahpot** [comment]
The Figma design:

Screen Shot 2021-08-19 at 9 13 13 pm

Appearance on my computer:

Screen Shot 2021-08-19 at 9 13 18 pm

There's a few things to resolve here:

- [ ] Need to set a maximum height to ensure the blue box maintains the correct aspect ratio.
- [ ] Need to ensure the box is aligned by vertically and horizontally.
- [ ] The `X` in the close button isn't exactly centred
- [ ] The white part of the background isn't positioned in the same as the Figma designs

**Comment by cmcWebCode40** [comment]
> The Figma design:
> 
> Screen Shot 2021-08-19 at 9 13 13 pm
> 
> Appearance on my computer:
> 
> Screen Shot 2021-08-19 at 9 13 18 pm
> 
> There's a few things to resolve here:
> 
> * [ ]  Need to set a maximum height to ensure the blue box maintains the correct aspect ratio.
> * [ ]  Need to ensure the box is aligned by vertically and horizontally.
> * [ ]  The `X` in the close button isn't exactly centred
> * [ ]  The white part of the background isn't positioned in the same as the Figma designs

noted

**Comment by nick-verida** [comment]
Media queries don't seem quite right:

at 1024px by 650px tall looks good:

image

at 600 it switches to the mobile layout (despite being 1024px wide):

image

If we go back to being 650px tall it remains in wide mode until below 700px wide even though the box is too big

image

**Review by nick-verida — APPROVED** [review]
Looks good

**Pull request merged**
